# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Connect_dtb_MySQL.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(814, 699)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setMinimumSize(QtCore.QSize(50, 50))
        self.scrollArea.setMaximumSize(QtCore.QSize(1300, 16777215))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 794, 638))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.query_edt = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.query_edt.setMaximumSize(QtCore.QSize(16777215, 160))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.query_edt.setFont(font)
        self.query_edt.setObjectName("query_edt")
        self.gridLayout_2.addWidget(self.query_edt, 7, 0, 1, 5)
        self.table_tbt = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.table_tbt.setFont(font)
        self.table_tbt.setAutoFillBackground(False)
        self.table_tbt.setGridStyle(QtCore.Qt.SolidLine)
        self.table_tbt.setObjectName("table_tbt")
        self.table_tbt.setColumnCount(0)
        self.table_tbt.setRowCount(0)
        self.gridLayout_2.addWidget(self.table_tbt, 1, 4, 4, 1)
        self.lineEdit_user = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_user.setObjectName("lineEdit_user")
        self.gridLayout_2.addWidget(self.lineEdit_user, 0, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 9, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 6, 0, 1, 1)
        self.connect_bt = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.connect_bt.setObjectName("connect_bt")
        self.gridLayout_2.addWidget(self.connect_bt, 3, 2, 1, 1)
        self.out_tbt = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.out_tbt.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.out_tbt.setFont(font)
        self.out_tbt.setObjectName("out_tbt")
        self.out_tbt.setColumnCount(0)
        self.out_tbt.setRowCount(0)
        self.gridLayout_2.addWidget(self.out_tbt, 10, 0, 1, 5)
        self.lineEdit_host = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_host.setObjectName("lineEdit_host")
        self.gridLayout_2.addWidget(self.lineEdit_host, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 3, 1, 1)
        self.lineEdit_pass = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_pass.setObjectName("lineEdit_pass")
        self.gridLayout_2.addWidget(self.lineEdit_pass, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 11, 0, 1, 3)
        self.comboBox_dtb = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBox_dtb.setObjectName("comboBox_dtb")
        self.gridLayout_2.addWidget(self.comboBox_dtb, 0, 4, 1, 1)
        self.query_bt = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.query_bt.setObjectName("query_bt")
        self.gridLayout_2.addWidget(self.query_bt, 8, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 3, 1, 1)
        self.disconnect_bt = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.disconnect_bt.setObjectName("disconnect_bt")
        self.gridLayout_2.addWidget(self.disconnect_bt, 4, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.decb_tb_bt = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.decb_tb_bt.setObjectName("decb_tb_bt")
        self.gridLayout_2.addWidget(self.decb_tb_bt, 5, 4, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 9, 1, 1, 4)
        self.expt_csv_bt = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.expt_csv_bt.setObjectName("expt_csv_bt")
        self.gridLayout_2.addWidget(self.expt_csv_bt, 12, 0, 1, 1)
        self.import_tb_bt = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.import_tb_bt.setObjectName("import_tb_bt")
        self.gridLayout_2.addWidget(self.import_tb_bt, 12, 1, 1, 1)
        self.chart_bt = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.chart_bt.setObjectName("chart_bt")
        self.gridLayout_2.addWidget(self.chart_bt, 12, 4, 1, 1)
        self.crt_tbt_bt = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.crt_tbt_bt.setObjectName("crt_tbt_bt")
        self.gridLayout_2.addWidget(self.crt_tbt_bt, 12, 2, 1, 2)
        self.exit_bt = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.exit_bt.setObjectName("exit_bt")
        self.gridLayout_2.addWidget(self.exit_bt, 13, 2, 1, 2)
        self.connect_St = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.connect_St.setAutoFillBackground(True)
        self.connect_St.setAlignment(QtCore.Qt.AlignCenter)
        self.connect_St.setObjectName("connect_St")
        self.gridLayout_2.addWidget(self.connect_St, 5, 2, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 5, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 814, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_user, self.lineEdit_host)
        MainWindow.setTabOrder(self.lineEdit_host, self.lineEdit_pass)
        MainWindow.setTabOrder(self.lineEdit_pass, self.connect_bt)
        MainWindow.setTabOrder(self.connect_bt, self.disconnect_bt)
        MainWindow.setTabOrder(self.disconnect_bt, self.comboBox_dtb)
        MainWindow.setTabOrder(self.comboBox_dtb, self.table_tbt)
        MainWindow.setTabOrder(self.table_tbt, self.decb_tb_bt)
        MainWindow.setTabOrder(self.decb_tb_bt, self.query_edt)
        MainWindow.setTabOrder(self.query_edt, self.query_bt)
        MainWindow.setTabOrder(self.query_bt, self.out_tbt)
        MainWindow.setTabOrder(self.out_tbt, self.scrollArea)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Connect MySQL DataBase"))
        self.query_edt.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "Output"))
        self.label_6.setText(_translate("MainWindow", "Query"))
        self.connect_bt.setText(_translate("MainWindow", "Connect"))
        self.out_tbt.setSortingEnabled(True)
        self.label_3.setText(_translate("MainWindow", "Password"))
        self.label_4.setText(_translate("MainWindow", "DataBase"))
        self.label.setText(_translate("MainWindow", "User"))
        self.query_bt.setText(_translate("MainWindow", "Run Query"))
        self.label_5.setText(_translate("MainWindow", "Tables"))
        self.disconnect_bt.setText(_translate("MainWindow", "Disconnect"))
        self.label_2.setText(_translate("MainWindow", "Host"))
        self.decb_tb_bt.setText(_translate("MainWindow", "Describe Table"))
        self.expt_csv_bt.setText(_translate("MainWindow", "Export CSV"))
        self.import_tb_bt.setText(_translate("MainWindow", "Import CSV"))
        self.chart_bt.setText(_translate("MainWindow", "Chart"))
        self.crt_tbt_bt.setText(_translate("MainWindow", "Create Table Database"))
        self.exit_bt.setText(_translate("MainWindow", "Exit"))
        self.connect_St.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Connection Station</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
